import React from 'react';
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './WifiInstructionsScreen.css';

export default function WifiInstructionsScreen() {
  const navigate = useNavigate();

  // const handleEnter = () => {
  //   window.location.href = 'http://192.168.178.86';
  // };

  useEffect(() => {
    const handleMessage = (event) => {
      console.log("Received:", event.data);

      if (event.data?.type === "ESP_PCB") {
        const pcbSerial = event.data.pcb;

        navigate("/machinescreen1", {
          state: {
            pcbSerial,
          },
        });
      }
    };

    window.addEventListener("message", handleMessage);

    return () => {
      window.removeEventListener("message", handleMessage);
    };
  }, [navigate]);

  const handleEnter = () => {
    window.open("http://192.168.178.86", "_blank");
  };


  const steps = [
    {
      text: <>On the display unit, navigate to <strong>Special Features</strong> and enable <strong>Wi-Fi Configure</strong> mode.</>,
      note: <>Once enabled, the unit will activate its hotspot for <strong>5 minutes</strong>.</>
    },
    {
      text: <>On your mobile phone, open <strong>Wi-Fi settings</strong> and connect to the <strong>ESP32 hotspot</strong> generated by the unit.</>
    },
    {
      text: <>Enter the hotspot password:</>,
      password: '12345678'
    },
    {
      text: <>After connecting to the ESP32 Wi-Fi network, press <strong>Enter</strong> in the mobile application.</>
    },
    {
      text: <>A new page will open — enter the following:</>,
      list: ['Wi-Fi SSID (network name)', 'Wi-Fi Password']
    },
    {
      text: <>After entering the credentials, press <strong>Submit</strong>.</>
    },
    {
      text: <>If successful, the <strong>PCB Serial Number</strong> will be displayed as confirmation that the motherboard has received and stored the credentials.</>
    },
  ];

  return (
    <div className="wfi-root">
      <div className="wfi-card">

        <div className="wfi-header">
          <svg width="44" height="44" viewBox="0 0 44 44" fill="none" className="wfi-svg" aria-hidden="true">
            <circle cx="22" cy="22" r="22" fill="#E3F2FD" />
            <path d="M9 20c3.5-3.5 8.2-5.5 13-5.5s9.5 2 13 5.5" stroke="#1976D2" strokeWidth="2.2" strokeLinecap="round"/>
            <path d="M13 24.5c2.3-2.3 5.4-3.7 9-3.7s6.7 1.4 9 3.7" stroke="#1976D2" strokeWidth="2.2" strokeLinecap="round"/>
            <path d="M17 29c1.2-1.2 2.9-2 5-2s3.8.8 5 2" stroke="#1976D2" strokeWidth="2.2" strokeLinecap="round"/>
            <circle cx="22" cy="33" r="1.8" fill="#1976D2"/>
          </svg>
          <div className="wfi-header-text">
            <h1 className="wfi-title">Wi-Fi Configuration</h1>
            <p className="wfi-subtitle">Follow the steps to configure your device</p>
          </div>
        </div>

        <div className="wfi-steps">
          {steps.map((step, i) => (
            <div className="wfi-step" key={i}>
              <div className="wfi-step-num">{i + 1}</div>
              <div className="wfi-step-body">
                <p className="wfi-step-text">{step.text}</p>
                {step.note && <div className="wfi-note">{step.note}</div>}
                {step.password && (
                  <div className="wfi-password">
                    <span className="wfi-pw-label">Password</span>
                    <span className="wfi-pw-value">{step.password}</span>
                  </div>
                )}
                {step.list && (
                  <ul className="wfi-list">
                    {step.list.map((item, j) => <li key={j}>{item}</li>)}
                  </ul>
                )}
              </div>
            </div>
          ))}
        </div>

        <div className="wfi-alert">
          <div className="wfi-alert-title">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" style={{flexShrink:0,marginTop:'2px'}}>
              <path d="M8 1.5L14.5 13H1.5L8 1.5Z" stroke="#B45309" strokeWidth="1.4" strokeLinejoin="round"/>
              <path d="M8 6v3.5" stroke="#B45309" strokeWidth="1.4" strokeLinecap="round"/>
              <circle cx="8" cy="11" r="0.75" fill="#B45309"/>
            </svg>
            Notes
          </div>
          <ul className="wfi-alert-list">
            <li>If not completed within <strong>5 minutes</strong>, the hotspot disables automatically. Repeat by enabling <strong>Wi-Fi Configure</strong> mode again.</li>
            <li>If the target network uses <strong>fixed MAC binding</strong> (MAC address filtering), the system will not be able to connect.</li>
          </ul>
        </div>

        <div className="wfi-actions">
          <button className="wfi-btn-back" onClick={() => navigate(-1)}>← Back</button>
          <button className="wfi-btn-enter" onClick={handleEnter}>Enter →</button>
        </div>

      </div>
    </div>
  );
}